import Head from 'next/head'
import Navbar from '../component/home/home'
import Collection from '../component/collection/collection'
import { theme } from '../utils/theme';
import {ThemeProvider,responsiveFontSizes} from '@material-ui/core';
import Feature from '../component/feature/feature'
import Products from '../component/products/products'
import Reviews from '../component/reviews/reviews'
import Gallery from '../component/gallery/gallery'
import Footer from '../component/footer/footer'



 let Theme = responsiveFontSizes(theme);

export default function Home() {
  return (
    <div>
      <Head>
        <title>HeadPhones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossOrigin="anonymous"/>  
      </Head>
      <ThemeProvider theme={Theme}>
         <Navbar />
         <Collection />
         <Feature />
		     <Products />
		     <Gallery />
		     <Reviews />
		     <Footer /> 
      </ThemeProvider> 

    </div>
  )
}
