import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../component/home'
import Collection from '../component/collection'
import styles from '../styles/Home.module.css'
import { theme } from './theme';
import {ThemeProvider,responsiveFontSizes} from '@material-ui/core';
import Feature from '../component/feature'
import Products from '../component/products'
import Reviews from '../component/reviews'
import Gallery from '../component/gallery'
import Footer from '../component/footer'



 let Theme = responsiveFontSizes(theme);

export default function Home() {
  return (
    <div>
      <Head>
        <title>HeadPhones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>  
      </Head>
      <ThemeProvider theme={Theme}>
        
         <Navbar />
         <Collection />
         <Feature />
		     <Products />
		     <Gallery />
		     <Reviews />
		     <Footer />
		 
         
      </ThemeProvider> 

    </div>
  )
}
