import React from 'react';
import Head from 'next/head';
import {CssBaseline,ThemeProvider} from '@material-ui/core';
import Footer from './footer' 
import Nav from './nav' 
import { theme } from '../utils/theme';

export default function Layout({children }) {
  


  return (
    <div>
      <Head>
         <title>cart</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
         <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossOrigin="anonymous"/>  
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <Nav />
	      {children}
	      <Footer />
      </ThemeProvider>
      
    </div>
  );
}